language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=LoopingThar/LoopingThar.ino
    - PLATFORMIO_CI_SRC=LoopingThar

install:
    - pip install -U platformio

script:
    - platformio ci --board=uno
